- name: Generate an encryption key
<<<<<<< HEAD
  shell: head -c 32 /dev/urandom | base64
  register: ENCRYPTION_KEY




#- name: Print encryption key value
#  debug:
#    msg: The value of encryption key is- "{{ ENCRYPTION_KEY }}"



=======
  command: ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)
>>>>>>> 33ee2ddefdafe0579811146bf155c6f5a8814241

- name: Copy encryption-config.yaml.j2
  template:
    src: "encryption-config.yaml.j2"
<<<<<<< HEAD
    dest: "{{ allcerts_dir }}/encryption-config.yaml"

=======
    dest: "encryption-config.yaml"

- name: Copy the encryption-config.yaml encryption config file to each controller instance
  
>>>>>>> 33ee2ddefdafe0579811146bf155c6f5a8814241
