#- name: Create binary directory
#  file:
#    path: '{{ allcerts_dir }}'
#    state: directory


- name: Download k8s binaries
  get_url:
    url: "{{ item }}"
    dest: "{{ allcerts_dir }}"
    mode: 0664
  with_items:
  - "{{ etcd_url }}"
  - "{{ kube_apiserver_url }}"
  - "{{ kube_controller_manager_url }}"
  - "{{ kube_scheduler_url }}"
  - "{{ kube_proxy_url }}"
  - "{{ kubelet_url }}"
  - "{{ kubectl_url }}"
  - "{{ cni_url }}"


- name: Extract and install the etcd server and the etcdctl command line utility
  shell: tar -xvf "{{ allcerts_dir }}/{{ etcd_tar }}"
  args:
    chdir: "{{ allcerts_dir }}"

